version: "3.9"
services:
    mysql:
        image: "mysql/mysql-server:8.0"
        ports:
            - "3310:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "demo"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
        volumes:
            - "mysql-volume:/var/lib/mysql"
        networks:
            - demo-local

networks:
    demo-local:
        driver: bridge

volumes:
    mysql-volume:
        driver: local
